[[datasets]]

[[datasets.subsets]]
num_repeats = 6
image_dir = "training_data/dataset_lora"

[general]
resolution = 512
shuffle_caption = false
keep_tokens = 1
flip_aug = false
caption_extension = ".txt"
enable_bucket = true
bucket_reso_steps = 64
bucket_no_upscale = false
min_bucket_reso = 256
max_bucket_reso = 1024
