[[datasets]]
resolution = 512
min_bucket_reso = 256
max_bucket_reso = 1024
caption_dropout_rate = 0
caption_tag_dropout_rate = 0
caption_dropout_every_n_epochs = 0
flip_aug = false
color_aug = false
[[datasets.subsets]]
image_dir = "/content/drive/MyDrive/Loras/red_hugo_logo/dataset"
class_tokens = "<red_hugo_logo> logo"
num_repeats = 6


[general]
enable_bucket = true
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
bucket_reso_steps = 64
bucket_no_upscale = false
